sudo: required
services:
  - docker

before_install:
  - docker build -t react-test -f Dockerfile.dev .

# `-- --coverage` is used to exit the test after running
# `-e CI=true` is used to exit the test after running, otherwise it will wait for user input, same as `-- --coverage`
script:
  - docker run -e CI=true  react-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend"
  env: "Frontend-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-225149677297"
  bucket_path: "frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY

# AWS_ACCESS_KEY and AWS_SECRET_KEY are stored in Travis CI environment variables
# They are stored in Travis CI environment variables to avoid exposing them in the public repositories