FROM node:16-alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .
# we can omit the copy step after setting up the volume since, whenever we run the container it's taking reference from the local machine so no need to copy the files
# but in production Dockerfile we need to copy the files

CMD ["npm", "run", "start"]